import { library } from '@fortawesome/fontawesome-svg-core';
import { fab } from '@fortawesome/free-brands-svg-icons';
import {
  faCalendarAlt,
  faClock,
  faCut,
  faDatabase,
  faTabletAlt,
  faUsers,
  faHome,
  faCog,
  faCashRegister,
  faTrash,
  faBox,
  faChartPie,
  faEdit,
  faUserTag,
  faHistory,
  faSearch,
  faSave,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  fab,
  faCalendarAlt,
  faCut,
  faTabletAlt,
  faDatabase,
  faClock,
  faUsers,
  faHome,
  faCog,
  faCashRegister,
  faTrash,
  faBox,
  faChartPie,
  faEdit,
  faUserTag,
  faHistory,
  faSearch,
  faSave,
);
